const KeyValue = {
  wfp_title: `{{title}} for {{price}}`,
  wfp_subtitle: `Extend your return window to 35 days`,
  wfp_description: `Get a full refund if the order doesn't arrive as described, including loss & damage in transit`,
  powered_by: `Powered by {{seel}}`,
  ineligible_main_message: `We're unable to offer Worry-Free Purchase® for this order. This could be due to one or more of the following reasons`,
  ineligible_reason_shipping: `Shipping destination not supported`,
  ineligible_reason_currency: `Checkout currency not accepted`,
  ineligible_reason_value: `Order value exceeds our coverage limit`,
  ineligible_reason_items: `Item(s) not eligible for this service`,
  ineligible_reason_system: `Our system has flagged this order as ineligible`,
  ineligible_support_message: `If you have any questions, please contact our customer support team for assistance`,
  ineligible_title: `Worry-Free Purchase® isn't eligible for this order`,
  coverage_title: `We've Got You Covered`,
  pricing_message: `Only {{price}} for Complete Peace of Mind`,
  product_name: `Worry-Free Purchase®`,
  whats_covered_title: `What's Covered`,
  standard_coverage_intro: `In addition to your standard coverage under consumer protection laws for`,
  standard_coverage_not_as_described: `Items not as described`,
  standard_coverage_lost_damaged: `Items lost, stolen or damaged in transit (i.e. before they are in your physical possession (or in the possession of someone you have authorised to take delivery)`,
  standard_coverage_not_matching: `Items not matching their description`,
  standard_coverage_quality: `Items not of satisfactory quality or not fit for purpose`,
  standard_coverage_not_delivered: `Items not delivered within 30 days of purchase, unless agreed otherwise`,
  additional_coverage_intro: `Worry-Free Purchase® provides the following protection`,
  additional_coverage_extended_return: `Extended return windows – Seven (7) additional days to decide`,
  additional_coverage_post_delivery: `Post-delivery theft coverage – Protection for packages stolen or missing after delivery`,
  additional_coverage_delay: `Delay compensation if the items are not delivered within 10 days`,
  concierge_intro: `Shoppers also get white glove concierge help with post purchase issues and mishaps`,
  concierge_app_access: `Access to desktop and mobile app`,
  concierge_support: `Live, instant support`,
  privacy_policy: `Privacy Policy`,
  terms_of_service: `Terms of Service`,
  cta_secure_purchase: `Secure Your Purchase Now`,
  cta_continue_without: `Continue Without Protection`,
  get_full_refund: `Get a Full Refund, No Questions Asked`,
  lost_in_transit: `Lost in-transit`,
  item_not_as_described: `Item arrived not as described`,
  item_damaged: `Item damaged/non-functional on arrival`,
  package_stolen: `Package stolen or missing after delivery`,
  easy_resolution: `Easy Resolution`,
  resolve_with_clicks: `Resolve your issues with just a few clicks`,
  complete_peace_of_mind: `Complete Peace of Mind`,
  zero_risk: `Zero-risk on your order with our protection`,
  get_refund_promptly: `Get your refund promptly`,
  worry_free_delivery: `Worry-Free Delivery®`,
};

export default KeyValue;
